# Package load hook: register all providers here
.onLoad <- function(libname, pkgname) {
  register_EE_EST()
  register_DK_VANDA()
  register_FI_SYKE()
  register_SE_SMHI()
  register_UK_NRFA()
  register_UK_CEH()
  register_LT_LHMT()
  register_IE_OPW()
  register_AU_BOM()
  register_BE_HIC()
  register_BE_WAL()
  register_FR_HUBEAU()
  register_PL_IMGW()
  register_CZ_CHMI()
  register_NO_NVE()
  register_BR_ANA()
  register_CA_ECCC()
  register_AT_EHYD()
  register_US_USGS_NWIS()
  register_US_USGS_DR()
  register_NL_RWS()
  register_JP_MLIT()
  register_RW_RWB()
  register_CL_DGA()
  register_SI_ARSO()
  register_ZA_DWS()
  # register_KR_WAMIS()
  register_ES_ROAN()
  register_AR_INA()
  register_CH_BAFU()
  register_BA_AVPS()
}
